# docker-compose.yml (root)
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  backend:
    build: ./backend
    environment:
      MONGODB_URI: mongodb://mongo:27017/appdb
      CORS_ORIGIN: http://localhost:5173
    depends_on: [mongo]
    ports: ["8080:8080"]

  frontend:
    build: ./frontend
    environment:
      # in docker we talk to backend on host: http://localhost:8080
      VITE_API_URL: http://localhost:8080
    depends_on: [backend]
    ports: ["5173:80"]

volumes:
  mongo_data:
