# src/main/resources/application.yml
spring:
  data:
    mongodb:
      uri: mongodb+srv://dayuser:oneday@mongome.9ezrhll.mongodb.net/daytoday?retryWrites=true&w=majority
      auto-index-creation: true
server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
