# src/main/resources/application.yml
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
